(function() {
    penPlus.cubemapFaceOrder = [
        "TEXTURE_CUBE_MAP_NEGATIVE_X",
        "TEXTURE_CUBE_MAP_POSITIVE_X",
        "TEXTURE_CUBE_MAP_NEGATIVE_Y",
        "TEXTURE_CUBE_MAP_POSITIVE_Y",
        "TEXTURE_CUBE_MAP_NEGATIVE_Z",
        "TEXTURE_CUBE_MAP_POSITIVE_Z"
    ];

    penPlus.shaderParams = penPlus.shaderParams || {};
    penPlus.shaderParams.sampleCubemaps = [
        {
        name: "Checker",
        DATA: [
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAADJJREFUOI1j/P/H4T8DHvBr+W180gxMeGWJAKMGDAYDGH8ulsabDtgiVWnrglEDBoMBAJGsCQ+QhljNAAAAAElFTkSuQmCC",//x-
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAC9JREFUOI1jvG+n/J8BD7j6iB2fNAMTXlkiwKgBg8EAFkLxrC33k7YuGDVgMBgAACfMBx9iMJK+AAAAAElFTkSuQmCC",//x+
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAC9JREFUOI1jrLRq+M+ABxz/eRmfNAMTXlkiwKgBg8EAFkLxbMmuS1sXjBowGAwAAFFMB+cg41JSAAAAAElFTkSuQmCC",//y-
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAC9JREFUOI1jnHPb+T8DHrD32Sd80gxMeGWJAKMGDAYDWAjFs7MUH21dMGrAYDAAAH0fCHDwLzvDAAAAAElFTkSuQmCC",//y+
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAC9JREFUOI1jjF3f+58BD7h69To+aQYmvLJEgFEDBoMBLITiWVtbk7YuGDVgMBgAAKXUCDsmk32CAAAAAElFTkSuQmCC",//z-
            "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAC9JREFUOI1jVJl/7z8DHsCy9xk+aQYmvLJEgFEDBoMBLITi+Y+zFG1dMGrAYDAAAFDBB2nIM9nbAAAAAElFTkSuQmCC"//z+
        ]
        },
    ];
})();